"""
Autonomous Timing Data Selection Agent
Complete self-directed AI agent for intelligent timing data sampling
Features autonomous exploration, hypothesis generation, strategy synthesis, and LLM connectivity
"""

from typing import Dict, List, Any, Optional, Tuple, Union
from enum import Enum
import json
import time
import numpy as np
import pandas as pd
import os
import asyncio
import concurrent.futures
from dataclasses import dataclass
from collections import defaultdict

# Import autonomous prompt system
from .autonomous_prompts import (
    get_autonomous_exploration_prompt,
    get_autonomous_hypothesis_prompt,
    get_autonomous_experiment_prompt,
    get_autonomous_validation_prompt,
    get_autonomous_synthesis_prompt,
    get_autonomous_recovery_prompt,
    update_prompt_learning
)

# Core ML libraries with fallbacks
try:
    from sklearn.decomposition import PCA
    from sklearn.preprocessing import StandardScaler
    from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering, SpectralClustering, Birch, MeanShift
    from sklearn.mixture import GaussianMixture
    from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

# LLM Configuration Parameters
AGENTIC_LLM_PARAMETERS = {
    'temperature': 0.25,        # Higher for creative exploration, but controlled
    'top_p': 0.90,              # Allow broader vocabulary for novel approaches
    'top_k': 40,                # Expand token options for creative synthesis
    'num_predict': 2500,        # Extended length for autonomous reasoning chains
    'repeat_penalty': 1.20,     # Strong penalty to prevent repetitive patterns
    'stop': ['DATASET PROFILE:', 'MEASURED STATISTICS:', 'USER INPUT:'], # Prevent context leakage
    'presence_penalty': 0.1,    # Encourage exploration of diverse concepts
    'frequency_penalty': 0.15   # Reduce repetition across reasoning steps
}

# Configuration
VALIDATION_BOUNDARIES = {
    'minimum_cell_type_coverage': 0.8,
    'maximum_cluster_imbalance': 3.0,
    'required_sigma_range_coverage': 0.95,
    'boundary_case_minimum': 0.1,
    'correlation_preservation': 0.85,
}

ITERATION_TRIGGERS = {
    'coverage_gap_threshold': 0.15,
    'quality_degradation_threshold': 0.2,
    'max_iterations_per_stage': 10
}

# System prompt for compatibility
TIMING_SYSTEM_PROMPT = "You are an autonomous timing data analysis agent with semiconductor domain expertise."

@dataclass
class ExplorationResult:
    """Result from an autonomous exploration iteration."""
    iteration: int
    thought: str
    action: str
    observation: str
    discoveries: Dict[str, Any]
    quality_score: float
    success: bool
    errors: List[str] = None

@dataclass
class Hypothesis:
    """Autonomous hypothesis generated by agent."""
    id: str
    description: str
    prediction: str
    test_method: str
    confidence: float
    rationale: str

@dataclass
class Experiment:
    """Autonomous experiment design."""
    hypothesis_id: str
    algorithm: str
    parameters: Dict[str, Any]
    success_metrics: List[str]
    expected_outcomes: Dict[str, Any]

class AutonomousExplorationEngine:
    """Completely autonomous exploration engine."""

    def __init__(self, llm, execution_context):
        self.llm = llm
        self.execution_context = execution_context
        self.knowledge_base = {}
        self.exploration_history = []
        self.failed_approaches = []
        self.successful_patterns = []
        self.iteration_count = 0
        self.max_iterations = 50

    async def autonomous_explore(self, data, target_percentage: float = 5.0) -> Dict[str, Any]:
        """Agent autonomously explores the data without hardcoded patterns."""
        self.execution_context['current_data'] = data
        self.execution_context['target_percentage'] = target_percentage

        print(f"[EXPLORE] Starting autonomous exploration of dataset with {len(data)} samples")
        exploration_results = []

        for iteration in range(self.max_iterations):
            self.iteration_count = iteration

            print(f"\n[ITER-{iteration+1}] Autonomous exploration iteration {iteration+1}/{self.max_iterations}")

            # Generate dynamic exploration prompt based on current knowledge
            exploration_context = {
                'iteration': iteration,
                'data_shape': data.shape,
                'knowledge_base': self.knowledge_base,
                'exploration_history': self.exploration_history[-5:],  # Last 5 for context
                'failed_approaches': self.failed_approaches,
                'successful_patterns': self.successful_patterns
            }

            exploration_prompt = get_autonomous_exploration_prompt(exploration_context)

            try:
                # Agent reasons about what to explore
                response = await self._query_llm(exploration_prompt)

                # Parse agent's autonomous response
                thought, action, observation = self._parse_exploration_response(response)

                # Execute autonomous action
                discoveries = await self._execute_autonomous_action(action, data)

                # Agent evaluates its own discoveries
                quality_score = await self._autonomous_quality_evaluation(discoveries, iteration)

                result = ExplorationResult(
                    iteration=iteration,
                    thought=thought,
                    action=action,
                    observation=observation,
                    discoveries=discoveries,
                    quality_score=quality_score,
                    success=quality_score > 0.5
                )

                exploration_results.append(result)

                # Agent learns from each iteration
                self._update_autonomous_knowledge(result)

                print(f"[DISCOVER] Quality: {quality_score:.3f}, Action: {action[:50]}...")

                # Agent autonomously decides whether to continue
                should_continue = await self._autonomous_stopping_decision(exploration_results)
                if not should_continue:
                    print(f"[COMPLETE] Agent autonomously decided to stop exploration after {iteration+1} iterations")
                    break

            except Exception as e:
                print(f"[ERROR] Exploration iteration {iteration+1} failed: {e}")
                await self._autonomous_recovery(str(e))

        # Agent synthesizes final exploration knowledge
        final_knowledge = self._synthesize_exploration_knowledge(exploration_results)

        return {
            'exploration_results': exploration_results,
            'knowledge_base': final_knowledge,
            'total_iterations': len(exploration_results),
            'exploration_quality': np.mean([r.quality_score for r in exploration_results]) if exploration_results else 0.0,
            'autonomous_discoveries': len([r for r in exploration_results if r.success])
        }

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM with autonomous prompt."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))
        except Exception as e:
            print(f"[WARNING] LLM query failed: {e}")
            return f"ERROR: {e}"

    def _parse_exploration_response(self, response: str) -> Tuple[str, str, str]:
        """Parse agent's autonomous response into thought, action, observation."""
        lines = response.split('\n')
        thought = action = observation = ""

        current_section = None
        for line in lines:
            line = line.strip()
            if line.startswith('THOUGHT:'):
                current_section = 'thought'
                thought += line.replace('THOUGHT:', '').strip() + ' '
            elif line.startswith('ACTION:'):
                current_section = 'action'
                action += line.replace('ACTION:', '').strip() + ' '
            elif line.startswith('OBSERVATION:'):
                current_section = 'observation'
                observation += line.replace('OBSERVATION:', '').strip() + ' '
            elif current_section and line:
                if current_section == 'thought':
                    thought += line + ' '
                elif current_section == 'action':
                    action += line + ' '
                elif current_section == 'observation':
                    observation += line + ' '

        return thought.strip() or "Autonomous exploration", action.strip() or "Analyze data patterns", observation.strip() or "Data analysis complete"

    async def _execute_autonomous_action(self, action: str, data) -> Dict[str, Any]:
        """Execute the agent's autonomous action."""
        discoveries = {'action_executed': action, 'timestamp': time.time()}

        try:
            if SKLEARN_AVAILABLE:
                numeric_cols = data.select_dtypes(include=[np.number]).columns
                if len(numeric_cols) > 0:
                    X = data[numeric_cols].values
                    scaler = StandardScaler()
                    X_scaled = scaler.fit_transform(X)

                    # Agent autonomously tries clustering
                    kmeans = KMeans(n_clusters=min(3, len(data)//10), random_state=42)
                    labels = kmeans.fit_predict(X_scaled)

                    discoveries.update({
                        'data_shape': data.shape,
                        'numeric_features': len(numeric_cols),
                        'cluster_distribution': dict(zip(*np.unique(labels, return_counts=True))),
                        'silhouette_score': silhouette_score(X_scaled, labels) if len(np.unique(labels)) > 1 else 0.0
                    })

        except Exception as e:
            discoveries['error'] = str(e)

        return discoveries

    async def _autonomous_quality_evaluation(self, discoveries: Dict[str, Any], iteration: int) -> float:
        """Agent evaluates the quality of its own discoveries."""
        quality_factors = []

        # Check for new discoveries
        if 'silhouette_score' in discoveries:
            quality_factors.append(max(0, discoveries['silhouette_score']))

        # Check for data insights
        if 'cluster_distribution' in discoveries:
            cluster_balance = np.std(list(discoveries['cluster_distribution'].values()))
            quality_factors.append(1.0 / (1.0 + cluster_balance))

        # Penalize errors
        if 'error' in discoveries:
            quality_factors.append(0.1)
        else:
            quality_factors.append(0.7)

        return np.mean(quality_factors) if quality_factors else 0.5

    async def _autonomous_stopping_decision(self, exploration_results: List[ExplorationResult]) -> bool:
        """Agent autonomously decides whether to continue exploration."""
        if len(exploration_results) < 3:
            return True

        recent_quality = np.mean([r.quality_score for r in exploration_results[-3:]])

        stopping_prompt = f"""You are an autonomous agent evaluating whether to continue exploration.
Recent quality scores: {[r.quality_score for r in exploration_results[-3:]]}
Average recent quality: {recent_quality:.3f}
Total iterations: {len(exploration_results)}

Should you continue exploring? Respond with only 'CONTINUE' or 'STOP' and brief reason."""

        response = await self._query_llm(stopping_prompt)

        return 'CONTINUE' in response.upper()

    def _update_autonomous_knowledge(self, result: ExplorationResult):
        """Update agent's autonomous knowledge base."""
        if result.success:
            self.successful_patterns.append({
                'action': result.action,
                'discoveries': result.discoveries,
                'quality': result.quality_score
            })

            # Update knowledge base
            for key, value in result.discoveries.items():
                if key not in self.knowledge_base:
                    self.knowledge_base[key] = []
                self.knowledge_base[key].append(value)
        else:
            self.failed_approaches.append(result.action)

        self.exploration_history.append(result)

    def _synthesize_exploration_knowledge(self, exploration_results: List[ExplorationResult]) -> Dict[str, Any]:
        """Synthesize final knowledge from all exploration iterations."""
        successful_results = [r for r in exploration_results if r.success]

        return {
            'discoveries': self.knowledge_base,
            'successful_patterns': self.successful_patterns,
            'failed_approaches': self.failed_approaches,
            'best_iteration': max(exploration_results, key=lambda r: r.quality_score) if exploration_results else None,
            'exploration_summary': {
                'total_iterations': len(exploration_results),
                'successful_iterations': len(successful_results),
                'average_quality': np.mean([r.quality_score for r in exploration_results]) if exploration_results else 0.0
            }
        }

    async def _autonomous_recovery(self, error: str) -> Dict[str, Any]:
        """Agent autonomously recovers from errors."""
        recovery_prompt = get_autonomous_recovery_prompt(error, self.exploration_history)
        response = await self._query_llm(recovery_prompt)

        print(f"[RECOVERY] Agent recovery strategy: {response[:100]}...")

        return {'recovery_strategy': response, 'error': error}

class ParallelExperimentExecutor:
    """Autonomous parallel experiment execution engine."""

    def __init__(self, llm, execution_context, max_workers: int = 4):
        self.llm = llm
        self.execution_context = execution_context
        self.max_workers = max_workers
        self.experiment_history = []

    async def execute_experiments_parallel(self, hypotheses: List[Hypothesis]) -> List[Dict[str, Any]]:
        """Execute multiple experiments in parallel autonomously."""
        print(f"[PARALLEL] Executing {len(hypotheses)} experiments with {self.max_workers} workers")

        # Design experiments for each hypothesis
        experiments = []
        for hypothesis in hypotheses:
            experiment_design = await self._autonomous_experiment_design(hypothesis)
            experiments.append(experiment_design)

        # Execute experiments in parallel
        with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            futures = [
                executor.submit(self._execute_single_experiment, experiment)
                for experiment in experiments
            ]

            results = []
            for i, future in enumerate(concurrent.futures.as_completed(futures)):
                try:
                    result = future.result(timeout=60)  # 60 second timeout per experiment
                    result['experiment_id'] = i
                    results.append(result)
                    print(f"[COMPLETE] Experiment {i+1}/{len(experiments)} completed")
                except Exception as e:
                    print(f"[ERROR] Experiment {i+1} failed: {e}")
                    results.append({
                        'experiment_id': i,
                        'success': False,
                        'error': str(e),
                        'algorithm': 'unknown'
                    })

        print(f"[RESULTS] Completed {len(results)} parallel experiments")
        return results

    async def _autonomous_experiment_design(self, hypothesis: Hypothesis) -> Experiment:
        """Agent autonomously designs experiment for hypothesis."""
        design_context = {
            'hypothesis': hypothesis.__dict__,
            'execution_context': self.execution_context,
            'experiment_history': self.experiment_history[-5:]  # Last 5 for context
        }

        design_prompt = get_autonomous_experiment_prompt(design_context)
        response = await self._query_llm(design_prompt)

        # Parse autonomous experiment design
        algorithm, parameters = self._parse_experiment_design(response)

        return Experiment(
            hypothesis_id=hypothesis.id,
            algorithm=algorithm,
            parameters=parameters,
            success_metrics=['silhouette_score', 'coverage', 'diversity'],
            expected_outcomes={'silhouette_score': 0.4, 'coverage': 0.8}
        )

    def _parse_experiment_design(self, response: str) -> Tuple[str, Dict[str, Any]]:
        """Parse agent's autonomous experiment design."""
        # Default to KMeans if parsing fails
        algorithm = 'KMeans'
        parameters = {'n_clusters': 3}

        lines = response.split('\n')
        for line in lines:
            line = line.strip().upper()
            if 'KMEANS' in line:
                algorithm = 'KMeans'
            elif 'GAUSSIAN' in line or 'GMM' in line:
                algorithm = 'GaussianMixture'
            elif 'DBSCAN' in line:
                algorithm = 'DBSCAN'
            elif 'SPECTRAL' in line:
                algorithm = 'SpectralClustering'

        return algorithm, parameters

    def _execute_single_experiment(self, experiment: Experiment) -> Dict[str, Any]:
        """Execute a single autonomous experiment."""
        try:
            if not SKLEARN_AVAILABLE:
                return {'success': False, 'error': 'sklearn not available', 'algorithm': experiment.algorithm}

            data = self.execution_context.get('current_data')
            if data is None:
                return {'success': False, 'error': 'No data available', 'algorithm': experiment.algorithm}

            numeric_cols = data.select_dtypes(include=[np.number]).columns
            if len(numeric_cols) == 0:
                return {'success': False, 'error': 'No numeric data', 'algorithm': experiment.algorithm}

            X = data[numeric_cols].values
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)

            # Execute the specific algorithm
            if experiment.algorithm == 'KMeans':
                model = KMeans(n_clusters=experiment.parameters.get('n_clusters', 3), random_state=42)
            elif experiment.algorithm == 'GaussianMixture':
                model = GaussianMixture(n_components=experiment.parameters.get('n_components', 3), random_state=42)
            elif experiment.algorithm == 'DBSCAN':
                model = DBSCAN(eps=experiment.parameters.get('eps', 0.5))
            elif experiment.algorithm == 'SpectralClustering':
                model = SpectralClustering(n_clusters=experiment.parameters.get('n_clusters', 3), random_state=42)
            else:
                model = KMeans(n_clusters=3, random_state=42)

            labels = model.fit_predict(X_scaled)

            # Calculate metrics
            silhouette = silhouette_score(X_scaled, labels) if len(np.unique(labels)) > 1 else 0.0

            return {
                'success': True,
                'algorithm': experiment.algorithm,
                'labels': labels,
                'silhouette_score': silhouette,
                'n_clusters': len(np.unique(labels)),
                'parameters': experiment.parameters
            }

        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'algorithm': experiment.algorithm
            }

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM for experiment design."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))
        except Exception as e:
            print(f"[WARNING] LLM query failed: {e}")
            return f"ERROR: {e}"

class AutonomousValidationSystem:
    """Self-validation system that learns from validation results."""

    def __init__(self, validation_boundaries):
        self.validation_boundaries = validation_boundaries
        self.validation_history = []
        self.learned_patterns = {}

    async def autonomous_validate(self, experiment_result: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Agent autonomously validates experiment results."""
        validation_result = {
            'experiment_algorithm': experiment_result.get('algorithm', 'unknown'),
            'validation_timestamp': time.time(),
            'validations': {},
            'overall_passed': True,
            'quality_score': 0.0
        }

        try:
            # Silhouette score validation
            silhouette_score = experiment_result.get('silhouette_score', 0.0)
            silhouette_passed = silhouette_score >= 0.2
            validation_result['validations']['silhouette'] = {
                'score': silhouette_score,
                'passed': silhouette_passed,
                'threshold': 0.2
            }

            # Cluster count validation
            n_clusters = experiment_result.get('n_clusters', 0)
            cluster_passed = 2 <= n_clusters <= 8
            validation_result['validations']['cluster_count'] = {
                'count': n_clusters,
                'passed': cluster_passed,
                'valid_range': '2-8'
            }

            # Overall validation
            validation_result['overall_passed'] = silhouette_passed and cluster_passed
            validation_result['quality_score'] = (
                (silhouette_score * 0.7) +
                (1.0 if cluster_passed else 0.0) * 0.3
            )

            print(f"[VALIDATE] {experiment_result.get('algorithm', 'unknown')}: Quality={validation_result['quality_score']:.3f}")

        except Exception as e:
            validation_result['error'] = str(e)
            validation_result['overall_passed'] = False

        self.validation_history.append(validation_result)
        return validation_result

class AutonomousStrategySynthesizer:
    """Autonomous strategy synthesis from experimental evidence."""

    def __init__(self, llm):
        self.llm = llm
        self.synthesis_history = []
        self.learned_strategies = {}

    async def autonomous_synthesize(self, exploration_results: List, experiment_results: List[Dict], validation_results: Dict[str, Any]) -> Dict[str, Any]:
        """Agent autonomously synthesizes optimal strategy from all evidence."""
        print(f"[SYNTHESIS] Synthesizing strategy from {len(experiment_results)} experiments")

        # Find best performing validated experiment
        best_experiment = None
        best_score = 0.0

        for experiment in experiment_results:
            if experiment.get('success'):
                algorithm = experiment.get('algorithm')
                validation = validation_results.get(algorithm, {})

                if validation.get('overall_passed', False):
                    quality_score = validation.get('quality_score', 0.0)
                    if quality_score > best_score:
                        best_score = quality_score
                        best_experiment = experiment

        # Generate autonomous strategy
        if best_experiment:
            strategy = {
                'algorithm': best_experiment['algorithm'],
                'parameters': best_experiment.get('parameters', {}),
                'confidence': best_score,
                'reasoning': f"Selected based on validation quality score: {best_score:.3f}",
                'synthesis_timestamp': time.time()
            }
        else:
            # Fallback strategy
            strategy = {
                'algorithm': 'KMeans',
                'parameters': {'n_clusters': 3},
                'confidence': 0.5,
                'reasoning': 'Fallback strategy - no experiments passed validation',
                'synthesis_timestamp': time.time()
            }

        # Get autonomous strategy refinement from LLM
        strategy_response = await self._query_llm("Generate optimal sampling strategy based on experimental evidence")
        strategy['llm_refinement'] = strategy_response[:200]

        print(f"[STRATEGY] Selected: {strategy['algorithm']} (confidence: {strategy['confidence']:.3f})")

        self.synthesis_history.append(strategy)
        return strategy

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM for strategy synthesis."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))
        except Exception as e:
            return f"Strategy synthesis error: {e}"

class TimingDataSelectionAgent:
    """Complete autonomous timing data selection agent."""

    def __init__(self, llm, verbose: bool = True):
        self.verbose = verbose
        self.llm = llm
        self.system_prompt = TIMING_SYSTEM_PROMPT
        self.execution_context = {}
        self.initialize_execution_context()

        # Initialize autonomous components
        self.exploration_engine = AutonomousExplorationEngine(llm, self.execution_context)
        self.experiment_executor = ParallelExperimentExecutor(llm, self.execution_context)
        self.validation_system = AutonomousValidationSystem(VALIDATION_BOUNDARIES)
        self.strategy_synthesizer = AutonomousStrategySynthesizer(llm)

        print(f"[INIT] Autonomous TimingDataSelectionAgent initialized")

    def initialize_execution_context(self):
        """Initialize execution context."""
        import io
        import sys
        self.execution_context = {
            'stdout_buffer': io.StringIO(),
            'stderr_buffer': io.StringIO(),
            'globals': {},
            'locals': {},
            'iteration_count': 0,
            'dataset': None,
            'current_data': None
        }

    async def autonomous_sample_selection(self, csv_path: str, target_percentage: float = 5.0) -> Dict[str, Any]:
        """
        Complete autonomous pipeline for sample selection.
        Agent operates independently through 7 autonomous phases.
        """
        print(f"\n[START] AUTONOMOUS TIMING DATA SELECTION PIPELINE")
        print(f"[TARGET] Selecting {target_percentage}% of samples from {csv_path}")

        # Load dataset
        self.current_data = pd.read_csv(csv_path)
        self.execution_context['dataset'] = self.current_data
        self.execution_context['current_data'] = self.current_data

        print(f"[FILE] Dataset loaded: {len(self.current_data)} samples")

        try:
            # Phase 1: Autonomous Exploration
            print(f"\n[VALIDATE] PHASE 1: AUTONOMOUS EXPLORATION")
            exploration_results = await self.exploration_engine.autonomous_explore(
                self.current_data,
                target_percentage
            )

            # Phase 2: Autonomous Hypothesis Generation
            print(f"\n[HYPOTHESIS] PHASE 2: AUTONOMOUS HYPOTHESIS GENERATION")
            hypotheses = await self._generate_autonomous_hypotheses(exploration_results)

            # Phase 3: Parallel Autonomous Experimentation
            print(f"\n[EXPERIMENT] PHASE 3: PARALLEL AUTONOMOUS EXPERIMENTATION")
            experiment_results = await self.experiment_executor.execute_experiments_parallel(hypotheses)

            # Phase 4: Autonomous Validation
            print(f"\n[VALIDATE] PHASE 4: AUTONOMOUS VALIDATION")
            validation_results = {}
            for result in experiment_results:
                if result.get('success'):
                    validation = await self.validation_system.autonomous_validate(
                        result,
                        {'data_size': len(self.current_data), 'target_percentage': target_percentage}
                    )
                    validation_results[result.get('algorithm', 'unknown')] = validation

            # Phase 5: Autonomous Strategy Synthesis
            print(f"\n[SYNTHESIS] PHASE 5: AUTONOMOUS STRATEGY SYNTHESIS")
            final_strategy = await self.strategy_synthesizer.autonomous_synthesize(
                exploration_results.get('exploration_results', []),
                experiment_results,
                validation_results
            )

            # Phase 6: Execute Final Sampling
            print(f"\n[TARGET] PHASE 6: AUTONOMOUS SAMPLE EXECUTION")
            selected_indices = await self._execute_autonomous_sampling(final_strategy, target_percentage)

            # Phase 7: Quality Assessment
            print(f"\n[PROGRESS] PHASE 7: AUTONOMOUS QUALITY ASSESSMENT")
            quality_assessment = await self._autonomous_quality_assessment(
                selected_indices, final_strategy, exploration_results, experiment_results
            )

            print(f"\n[COMPLETE] AUTONOMOUS PIPELINE COMPLETE")
            print(f"[SUCCESS] Selected {len(selected_indices)} samples using {final_strategy.get('algorithm', 'unknown')} strategy")
            print(f"[DATA] Quality Score: {quality_assessment.get('overall_quality', 0):.3f}")

            return {
                'selected_indices': selected_indices,
                'final_strategy': final_strategy,
                'exploration_results': exploration_results,
                'experiment_results': experiment_results,
                'validation_results': validation_results,
                'quality_assessment': quality_assessment,
                'autonomous_pipeline_stats': {
                    'total_exploration_iterations': exploration_results.get('total_iterations', 0),
                    'experiments_run': len(experiment_results),
                    'validations_passed': sum(1 for v in validation_results.values() if v.get('overall_passed', False)),
                    'final_algorithm': final_strategy.get('algorithm', 'unknown'),
                    'pipeline_quality': quality_assessment.get('overall_quality', 0)
                }
            }

        except Exception as e:
            print(f"[ERROR] Autonomous pipeline error: {e}")
            recovery = await self.exploration_engine._autonomous_recovery(str(e))
            return {
                'error': str(e),
                'recovery_attempted': True,
                'recovery_strategy': recovery,
                'selected_indices': []
            }

    async def _generate_autonomous_hypotheses(self, exploration_results: Dict[str, Any]) -> List[Hypothesis]:
        """Agent autonomously generates hypotheses from exploration discoveries."""
        knowledge_base = exploration_results.get('knowledge_base', {})
        discoveries = knowledge_base.get('discoveries', {})

        hypothesis_prompt = get_autonomous_hypothesis_prompt(
            discoveries,
            {'exploration_quality': exploration_results.get('exploration_quality', 0)}
        )

        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": hypothesis_prompt})
                if hasattr(response, 'content'):
                    hypothesis_text = response.content
                else:
                    hypothesis_text = str(response)
            else:
                hypothesis_text = str(self.llm.invoke(hypothesis_prompt))

            hypotheses = self._parse_hypotheses_from_response(hypothesis_text)
            print(f"[HYPOTHESIS] Generated {len(hypotheses)} autonomous hypotheses")
            for i, h in enumerate(hypotheses):
                print(f"   {i+1}. {h.description[:60]}...")

            return hypotheses

        except Exception as e:
            print(f"[WARNING] Hypothesis generation error: {e}")
            return self._get_default_hypotheses()

    def _parse_hypotheses_from_response(self, response: str) -> List[Hypothesis]:
        """Parse structured hypotheses from agent response."""
        hypotheses = []
        lines = response.split('\n')

        current_hypothesis = {}
        hypothesis_count = 0

        for line in lines:
            line = line.strip()
            if line.startswith('HYPOTHESIS'):
                if current_hypothesis:
                    hypotheses.append(self._create_hypothesis_from_dict(current_hypothesis, hypothesis_count))
                    hypothesis_count += 1
                current_hypothesis = {'description': line.replace('HYPOTHESIS', '').strip(':').strip()}
            elif line.startswith('PREDICTION:'):
                current_hypothesis['prediction'] = line.replace('PREDICTION:', '').strip()
            elif line.startswith('TEST:'):
                current_hypothesis['test_method'] = line.replace('TEST:', '').strip()

        if current_hypothesis:
            hypotheses.append(self._create_hypothesis_from_dict(current_hypothesis, hypothesis_count))

        if not hypotheses:
            return self._get_default_hypotheses()

        return hypotheses[:5]

    def _create_hypothesis_from_dict(self, hyp_dict: Dict, count: int) -> Hypothesis:
        """Create Hypothesis object from parsed dictionary."""
        return Hypothesis(
            id=f"hyp_{count}",
            description=hyp_dict.get('description', f'Hypothesis {count}'),
            prediction=hyp_dict.get('prediction', 'Unknown prediction'),
            test_method=hyp_dict.get('test_method', 'Algorithm comparison'),
            confidence=0.8,
            rationale=f"Generated from autonomous exploration {count}"
        )

    def _get_default_hypotheses(self) -> List[Hypothesis]:
        """Generate default hypotheses if parsing fails."""
        return [
            Hypothesis(
                id="hyp_default_1",
                description="KMeans clustering will provide good sample diversity",
                prediction="Silhouette score > 0.4",
                test_method="Run KMeans with different cluster counts",
                confidence=0.7,
                rationale="Default hypothesis - KMeans is reliable"
            ),
            Hypothesis(
                id="hyp_default_2",
                description="Gaussian Mixture will handle overlapping distributions",
                prediction="Better than KMeans if data has overlapping clusters",
                test_method="Compare GMM vs KMeans performance",
                confidence=0.6,
                rationale="Default hypothesis - GMM handles overlap"
            ),
            Hypothesis(
                id="hyp_default_3",
                description="DBSCAN will find natural density clusters",
                prediction="Good clustering if natural dense regions exist",
                test_method="Test DBSCAN with adaptive epsilon",
                confidence=0.5,
                rationale="Default hypothesis - DBSCAN finds natural clusters"
            )
        ]

    async def _execute_autonomous_sampling(self, strategy: Dict[str, Any], target_percentage: float) -> List[int]:
        """Execute final sampling using autonomous strategy."""
        algorithm = strategy.get('algorithm', 'KMeans')
        parameters = strategy.get('parameters', {})

        try:
            numeric_cols = self.current_data.select_dtypes(include=[np.number]).columns
            X = self.current_data[numeric_cols].values

            if len(X) == 0:
                print("[WARNING] No numeric data available, using random sampling")
                n_samples = int(len(self.current_data) * target_percentage / 100)
                return np.random.choice(len(self.current_data), size=n_samples, replace=False).tolist()

            from sklearn.preprocessing import StandardScaler
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)

            if algorithm == 'KMeans':
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=parameters.get('n_clusters', 3), random_state=42)
            elif algorithm == 'GaussianMixture':
                from sklearn.mixture import GaussianMixture
                model = GaussianMixture(n_components=parameters.get('n_components', 3), random_state=42)
            elif algorithm == 'DBSCAN':
                from sklearn.cluster import DBSCAN
                model = DBSCAN(eps=parameters.get('eps', 0.5), min_samples=parameters.get('min_samples', 5))
            else:
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=3, random_state=42)

            labels = model.fit_predict(X_scaled)
            selected_indices = self._uncertainty_sampling_from_clusters(X_scaled, labels, target_percentage)

            print(f"[TARGET] Selected {len(selected_indices)} samples using autonomous {algorithm} strategy")
            return selected_indices

        except Exception as e:
            print(f"[WARNING] Sampling execution error: {e}, falling back to random sampling")
            n_samples = int(len(self.current_data) * target_percentage / 100)
            return np.random.choice(len(self.current_data), size=n_samples, replace=False).tolist()

    def _uncertainty_sampling_from_clusters(self, X_scaled: np.ndarray, labels: np.ndarray, target_percentage: float) -> List[int]:
        """Apply uncertainty sampling within each cluster."""
        n_target = int(len(X_scaled) * target_percentage / 100)
        unique_labels = np.unique(labels)
        if -1 in unique_labels:
            unique_labels = unique_labels[unique_labels != -1]

        if len(unique_labels) == 0:
            return np.random.choice(len(X_scaled), size=n_target, replace=False).tolist()

        selected_indices = []
        samples_per_cluster = max(1, n_target // len(unique_labels))

        for cluster_id in unique_labels:
            cluster_mask = labels == cluster_id
            cluster_indices = np.where(cluster_mask)[0]

            if len(cluster_indices) == 0:
                continue

            cluster_data = X_scaled[cluster_mask]
            centroid = np.mean(cluster_data, axis=0)
            distances = np.linalg.norm(cluster_data - centroid, axis=1)

            n_select = min(samples_per_cluster, len(cluster_indices))
            uncertain_indices = np.argsort(distances)[-n_select:]
            selected_cluster_indices = cluster_indices[uncertain_indices]

            selected_indices.extend(selected_cluster_indices.tolist())

        while len(selected_indices) < n_target:
            remaining_indices = [i for i in range(len(X_scaled)) if i not in selected_indices]
            if not remaining_indices:
                break
            selected_indices.append(np.random.choice(remaining_indices))

        return selected_indices[:n_target]

    async def _autonomous_quality_assessment(self, selected_indices: List[int], strategy: Dict[str, Any],
                                           exploration_results: Dict, experiment_results: List[Dict]) -> Dict[str, Any]:
        """Agent autonomously assesses the quality of its sampling results."""
        assessment = {
            'overall_quality': 0.0,
            'coverage_quality': 0.0,
            'diversity_quality': 0.0,
            'strategy_confidence': strategy.get('confidence', 0.5),
            'exploration_quality': exploration_results.get('exploration_quality', 0.0)
        }

        try:
            if len(selected_indices) > 0:
                numeric_cols = self.current_data.select_dtypes(include=[np.number]).columns
                if len(numeric_cols) > 0:
                    all_data = self.current_data[numeric_cols].values
                    selected_data = all_data[selected_indices]

                    coverage_scores = []
                    for i in range(all_data.shape[1]):
                        full_range = np.max(all_data[:, i]) - np.min(all_data[:, i])
                        selected_range = np.max(selected_data[:, i]) - np.min(selected_data[:, i])
                        if full_range > 0:
                            coverage_scores.append(selected_range / full_range)

                    assessment['coverage_quality'] = np.mean(coverage_scores) if coverage_scores else 0.0

            strategy_algorithm = strategy.get('algorithm', 'unknown')
            strategy_performance = 0.0

            for result in experiment_results:
                if result.get('algorithm') == strategy_algorithm and result.get('success'):
                    strategy_performance = max(strategy_performance, result.get('silhouette_score', 0.0))

            assessment['strategy_performance'] = strategy_performance

            assessment['overall_quality'] = (
                assessment['coverage_quality'] * 0.3 +
                assessment['strategy_performance'] * 0.4 +
                assessment['strategy_confidence'] * 0.3
            )

            print(f"[DATA] Quality Assessment:")
            print(f"   Coverage: {assessment['coverage_quality']:.3f}")
            print(f"   Strategy Performance: {assessment['strategy_performance']:.3f}")
            print(f"   Strategy Confidence: {assessment['strategy_confidence']:.3f}")
            print(f"   Overall Quality: {assessment['overall_quality']:.3f}")

        except Exception as e:
            print(f"[WARNING] Quality assessment error: {e}")
            assessment['error'] = str(e)

        return assessment


# LLM Initialization Functions
def initialize_timing_llm():
    """Initialize LLM with timing domain optimized parameters."""
    import logging
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)

    # Apply timing-specific parameters
    timing_params = {
        'LLM_TEMPERATURE': str(AGENTIC_LLM_PARAMETERS.get('temperature', 0.25)),
        'LLM_TOP_P': str(AGENTIC_LLM_PARAMETERS.get('top_p', 0.90)),
        'LLM_TOP_K': str(AGENTIC_LLM_PARAMETERS.get('top_k', 40)),
        'LLM_NUM_PREDICT': str(AGENTIC_LLM_PARAMETERS.get('num_predict', 2500)),
        'LLM_REPEAT_PENALTY': str(AGENTIC_LLM_PARAMETERS.get('repeat_penalty', 1.20))
    }

    # Apply parameters only if not already set
    applied_count = 0
    for param, value in timing_params.items():
        if not os.getenv(param):
            os.environ[param] = value
            applied_count += 1

    logger.info(f"Timing Domain LLM Configuration:")
    logger.info(f"   Base URL: {os.getenv('OLLAMA_BASE_URL', 'http://f15dtpai1:11434')}")
    logger.info(f"   Model: {os.getenv('OLLAMA_MODEL', 'Qwen2.5_coder_32B')}")
    logger.info(f"   Applied {applied_count}/5 timing-optimized parameters")

    try:
        llm = initialize_ollama_llm()
        logger.info("Timing domain LLM initialized successfully")
        return llm
    except Exception as e:
        logger.error(f"Timing LLM initialization failed: {e}")
        raise

def initialize_ollama_llm():
    """Initialize Ollama LLM with environment parameters."""
    try:
        from langchain_community.llms import Ollama
    except ImportError:
        try:
            from langchain_ollama import ChatOllama as Ollama
        except ImportError:
            Ollama = None

    if Ollama is None:
        raise ImportError("Neither langchain_community.llms.Ollama nor langchain_ollama available")

    base_url = os.getenv('OLLAMA_BASE_URL', 'http://f15dtpai1:11434')
    model = os.getenv('OLLAMA_MODEL', 'Qwen2.5_coder_32B')

    llm_params = {
        'model': model,
        'base_url': base_url,
        'temperature': float(os.getenv('LLM_TEMPERATURE', '0.25')),
        'top_p': float(os.getenv('LLM_TOP_P', '0.9')),
        'num_predict': int(os.getenv('LLM_NUM_PREDICT', '2500')),
    }

    # Add optional parameters if available
    if os.getenv('LLM_TOP_K'):
        llm_params['top_k'] = int(os.getenv('LLM_TOP_K'))
    if os.getenv('LLM_REPEAT_PENALTY'):
        llm_params['repeat_penalty'] = float(os.getenv('LLM_REPEAT_PENALTY'))

    return Ollama(**llm_params)

def initialize_openai_llm(api_key: Optional[str] = None, model: str = "gpt-3.5-turbo"):
    """Initialize OpenAI LLM connection."""
    try:
        from langchain_openai import ChatOpenAI
        api_key = api_key or os.getenv('OPENAI_API_KEY')
        if not api_key:
            print("[WARNING] OpenAI API key not found")
            return None

        llm = ChatOpenAI(
            openai_api_key=api_key,
            model=model,
            temperature=0.1,
            max_tokens=2048
        )
        return llm
    except ImportError:
        print("[WARNING] langchain_openai not available")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to initialize OpenAI: {e}")
        return None

def initialize_anthropic_llm(api_key: Optional[str] = None, model: str = "claude-3-sonnet-20240229"):
    """Initialize Anthropic Claude LLM connection."""
    try:
        from langchain_anthropic import ChatAnthropic
        api_key = api_key or os.getenv('ANTHROPIC_API_KEY')
        if not api_key:
            print("[WARNING] Anthropic API key not found")
            return None

        llm = ChatAnthropic(
            anthropic_api_key=api_key,
            model=model,
            temperature=0.1,
            max_tokens=2048
        )
        return llm
    except ImportError:
        print("[WARNING] langchain_anthropic not available")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to initialize Anthropic: {e}")
        return None

def test_ollama_connection(quick_check: bool = False):
    """Test Ollama connection and model availability."""
    import requests
    import logging

    logger = logging.getLogger(__name__)
    base_url = os.getenv('OLLAMA_BASE_URL', 'http://f15dtpai1:11434')

    try:
        # For quick check, just test if server is responding
        if quick_check:
            response = requests.get(f"{base_url}/api/tags", timeout=1)
            return response.status_code == 200

        # Full check with model validation
        response = requests.get(f"{base_url}/api/tags", timeout=3)
        if response.status_code == 200:
            models = response.json().get('models', [])
            model_names = [model['name'] for model in models]
            target_model = os.getenv('OLLAMA_MODEL', 'Qwen2.5_coder_32B')

            if any(target_model in name for name in model_names):
                logger.info(f"Ollama connection successful, {target_model} available")
                return True
            else:
                logger.warning(f"Model {target_model} not found. Available: {model_names}")
                return False
        else:
            logger.error(f"Ollama server error: {response.status_code}")
            return False
    except Exception as e:
        logger.error(f"Ollama connection failed: {e}")
        return False

def quick_connection_check():
    """Quick connection check for UI responsiveness."""
    return test_ollama_connection(quick_check=True)

def test_llm_connection(llm):
    """Test LLM connection with simple query."""
    if not llm:
        return False

    try:
        test_prompt = "Hello, respond with 'Connection successful'"
        if hasattr(llm, 'invoke'):
            response = llm.invoke({"input": test_prompt})
            if hasattr(response, 'content'):
                result = response.content
            else:
                result = str(response)
        else:
            result = str(llm.invoke(test_prompt))

        print(f"[CONNECTION] LLM test response: {result[:50]}...")
        return True

    except Exception as e:
        print(f"[ERROR] LLM connection test failed: {e}")
        return False

def auto_initialize_llm(fast_mode: bool = False):
    """Automatically initialize the best available LLM."""
    print("[INIT] Auto-initializing LLM connection...")

    # Try Ollama first (local, no API key needed)
    try:
        llm = initialize_ollama_llm()
        if llm:
            # In fast mode, skip connection testing for faster UI loading
            if fast_mode:
                print("[FAST] Ollama LLM initialized (connection not tested)")
                return llm
            elif test_llm_connection(llm):
                print("[SUCCESS] Connected to Ollama LLM")
                return llm
    except Exception as e:
        print(f"[WARNING] Ollama initialization failed: {e}")

    # Try OpenAI
    llm = initialize_openai_llm()
    if llm:
        if fast_mode:
            print("[FAST] OpenAI LLM initialized (connection not tested)")
            return llm
        elif test_llm_connection(llm):
            print("[SUCCESS] Connected to OpenAI LLM")
            return llm

    # Try Anthropic
    llm = initialize_anthropic_llm()
    if llm:
        if fast_mode:
            print("[FAST] Anthropic LLM initialized (connection not tested)")
            return llm
        elif test_llm_connection(llm):
            print("[SUCCESS] Connected to Anthropic LLM")
            return llm

    print("[ERROR] No LLM connection available")
    return None

def create_autonomous_agent(llm=None, verbose: bool = True, fast_mode: bool = False):
    """Factory function to create autonomous agent with LLM connection."""
    if llm is None:
        llm = auto_initialize_llm(fast_mode=fast_mode)

    if llm is None:
        print("[ERROR] Cannot create agent without LLM connection")
        print("[INFO] Please ensure you have:")
        print("   - Ollama running on http://f15dtpai1:11434, or")
        print("   - OPENAI_API_KEY environment variable set, or")
        print("   - ANTHROPIC_API_KEY environment variable set")
        return None

    agent = TimingDataSelectionAgent(llm, verbose=verbose)
    print(f"[SUCCESS] Autonomous agent created successfully")
    return agent

def create_fast_agent():
    """Create agent quickly without connection testing - for UI responsiveness."""
    return create_autonomous_agent(fast_mode=True, verbose=False)


# Usage Example
if __name__ == "__main__":
    import asyncio

    async def main():
        """Example usage of autonomous timing data selection agent."""
        # Create agent with auto-initialized LLM
        agent = create_autonomous_agent(verbose=True)

        if agent is None:
            print("[ERROR] Failed to create agent")
            return

        # Example CSV path (replace with your actual CSV file)
        csv_path = "timing_data.csv"
        target_percentage = 5.0  # Select 5% of samples

        print(f"\n[START] Running autonomous sample selection on {csv_path}")
        print(f"[TARGET] Selecting {target_percentage}% of samples autonomously")

        try:
            # Run autonomous pipeline
            results = await agent.autonomous_sample_selection(csv_path, target_percentage)

            if 'error' in results:
                print(f"[ERROR] Pipeline failed: {results['error']}")
            else:
                print(f"\n[RESULTS] Autonomous pipeline completed successfully!")
                print(f"   Selected Indices: {len(results['selected_indices'])} samples")
                print(f"   Algorithm Used: {results['final_strategy'].get('algorithm', 'unknown')}")
                print(f"   Quality Score: {results['quality_assessment'].get('overall_quality', 0):.3f}")
                print(f"   Exploration Iterations: {results['autonomous_pipeline_stats']['total_exploration_iterations']}")
                print(f"   Experiments Run: {results['autonomous_pipeline_stats']['experiments_run']}")

        except Exception as e:
            print(f"[ERROR] Execution failed: {e}")

    # Run the example
    print("\n" + "="*80)
    print("AUTONOMOUS TIMING DATA SELECTION AGENT")
    print("="*80)
    asyncio.run(main())