"""
Autonomous Timing Data Selection Agent - Minimal Version
Completely self-directed AI agent for intelligent timing data sampling
"""

from typing import Dict, List, Any, Optional, Tuple, Union
from enum import Enum
import json
import time
import numpy as np
import pandas as pd
import os
import asyncio
import concurrent.futures
from dataclasses import dataclass
from collections import defaultdict

# Import autonomous prompt system
from .autonomous_prompts import (
    get_autonomous_exploration_prompt,
    get_autonomous_hypothesis_prompt,
    get_autonomous_experiment_prompt,
    get_autonomous_validation_prompt,
    get_autonomous_synthesis_prompt,
    get_autonomous_recovery_prompt,
    update_prompt_learning
)

# Core ML libraries with fallbacks
try:
    from sklearn.decomposition import PCA
    from sklearn.preprocessing import StandardScaler
    from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering, SpectralClustering, Birch, MeanShift
    from sklearn.mixture import GaussianMixture
    from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

# Configuration
VALIDATION_BOUNDARIES = {
    'minimum_cell_type_coverage': 0.8,
    'maximum_cluster_imbalance': 3.0,
    'required_sigma_range_coverage': 0.95,
    'boundary_case_minimum': 0.1,
    'correlation_preservation': 0.85,
}

ITERATION_TRIGGERS = {
    'coverage_gap_threshold': 0.15,
    'quality_degradation_threshold': 0.2,
    'max_iterations_per_stage': 10
}

# Simple system prompt for compatibility
TIMING_SYSTEM_PROMPT = "You are an autonomous timing data analysis agent with semiconductor domain expertise."

@dataclass
class ExplorationResult:
    """Result from an autonomous exploration iteration."""
    iteration: int
    thought: str
    action: str
    observation: str
    discoveries: Dict[str, Any]
    quality_score: float
    success: bool
    errors: List[str] = None

@dataclass
class Hypothesis:
    """Autonomous hypothesis generated by agent."""
    id: str
    description: str
    prediction: str
    test_method: str
    confidence: float
    rationale: str

@dataclass
class Experiment:
    """Autonomous experiment design."""
    hypothesis_id: str
    algorithm: str
    parameters: Dict[str, Any]
    success_metrics: List[str]
    expected_outcomes: Dict[str, Any]

class AutonomousExplorationEngine:
    """Completely autonomous exploration engine."""

    def __init__(self, llm, execution_context):
        self.llm = llm
        self.execution_context = execution_context
        self.knowledge_base = {}
        self.exploration_history = []
        self.failed_approaches = []
        self.successful_patterns = []
        self.iteration_count = 0
        self.max_iterations = 50

    async def autonomous_explore(self, dataset, target_percentage: float) -> Dict[str, Any]:
        """Completely autonomous exploration."""
        self.knowledge_base = {
            'dataset_size': len(dataset),
            'target_percentage': target_percentage,
            'target_count': int(len(dataset) * target_percentage / 100),
            'discoveries': {},
            'open_questions': [
                'What are the key features?',
                'What patterns exist in the data?',
                'What sampling strategy would work best?'
            ]
        }

        exploration_results = []
        print(f"\n[EXPLORATION] Starting autonomous exploration (max {self.max_iterations} iterations)")
        print(f"[EXPLORATION] Dataset: {len(dataset)} samples, target: {target_percentage}%")

        while not await self._should_stop_exploration():
            self.iteration_count += 1
            print(f"\n[EXPLORATION] Autonomous Iteration {self.iteration_count}")

            try:
                result = await self._autonomous_exploration_step()
                exploration_results.append(result)
                self._update_knowledge_base(result)

                progress_assessment = await self._assess_exploration_progress()
                print(f"[SUCCESS] Quality Score: {result.quality_score:.3f}")
                print(f"[PROGRESS] Progress: {progress_assessment['completion_percentage']:.1f}%")

                if progress_assessment['should_stop']:
                    print(f"[TARGET] Agent satisfied with exploration after {self.iteration_count} iterations")
                    break

            except Exception as e:
                print(f"[ERROR] Exploration error: {e}")
                recovery = await self._autonomous_recovery(str(e))
                if not recovery['can_continue']:
                    break

        print(f"\n[COMPLETE] Autonomous exploration complete: {len(exploration_results)} iterations")

        return {
            'exploration_results': exploration_results,
            'knowledge_base': self.knowledge_base,
            'total_iterations': len(exploration_results),
            'exploration_quality': await self._assess_overall_quality()
        }

    async def _autonomous_exploration_step(self) -> ExplorationResult:
        """Single autonomous exploration step."""
        context = {
            'iteration': self.iteration_count,
            'knowledge_gaps': self.knowledge_base.get('open_questions', []),
            'discoveries': self.knowledge_base.get('discoveries', {}),
            'data_size': self.knowledge_base.get('dataset_size', 0),
            'previous_results': self.exploration_history[-3:] if self.exploration_history else []
        }

        exploration_prompt = get_autonomous_exploration_prompt(context)
        print(f"[THINK] Agent thinking...")

        response = await self._query_llm(exploration_prompt)
        thought, action = self._parse_thought_action(response)

        print(f"[THOUGHT] Thought: {thought[:100]}...")
        print(f"[ACTION] Action: Executing autonomous code...")

        observation = self._execute_autonomous_action(action)
        discoveries = self._extract_discoveries_autonomous(observation, context)
        quality_score = self._evaluate_iteration_quality(discoveries, observation)

        result = ExplorationResult(
            iteration=self.iteration_count,
            thought=thought,
            action=action,
            observation=observation,
            discoveries=discoveries,
            quality_score=quality_score,
            success='ERROR' not in observation
        )

        self.exploration_history.append(result)
        return result

    async def _should_stop_exploration(self) -> bool:
        """Agent autonomously decides when to stop exploration."""
        if self.iteration_count >= self.max_iterations:
            return True
        if self.iteration_count < 3:
            return False

        context = {
            'iteration_count': self.iteration_count,
            'knowledge_base': self.knowledge_base,
            'recent_quality': [r.quality_score for r in self.exploration_history[-3:]],
            'discoveries': self.knowledge_base.get('discoveries', {})
        }

        stopping_prompt = f"""
        You have been exploring for {self.iteration_count} iterations.
        Current knowledge: {len(self.knowledge_base.get('discoveries', {}))} discoveries
        Recent quality scores: {context['recent_quality']}
        Open questions: {len(self.knowledge_base.get('open_questions', []))}

        Should you stop exploration? Consider:
        - Do you understand the dataset well enough for sampling?
        - Are you discovering diminishing new insights?
        - Do you have enough information to make sampling decisions?

        Respond with: CONTINUE or STOP with brief reasoning.
        """

        response = await self._query_llm(stopping_prompt)
        return 'STOP' in response.upper()

    def _execute_autonomous_action(self, action_code: str) -> str:
        """Execute agent's autonomously generated code."""
        try:
            if 'dataset' not in self.execution_context:
                self.execution_context['dataset'] = self.execution_context.get('current_data')

            import io
            import sys
            old_stdout = sys.stdout
            sys.stdout = captured_output = io.StringIO()

            exec(action_code, self.execution_context)

            sys.stdout = old_stdout
            output = captured_output.getvalue()
            return output if output.strip() else "Code executed successfully (no output)"

        except Exception as e:
            return f"ERROR: {str(e)}"

    def _extract_discoveries_autonomous(self, observation: str, context: Dict) -> Dict[str, Any]:
        """Agent autonomously extracts discoveries from its observations."""
        discoveries = {}

        if 'columns' in observation.lower():
            lines = observation.split('\n')
            for line in lines:
                if 'columns' in line.lower():
                    discoveries['schema_analysis'] = line.strip()

        if 'shape' in observation.lower():
            lines = observation.split('\n')
            for line in lines:
                if 'shape' in line.lower():
                    discoveries['data_shape'] = line.strip()

        if any(word in observation.lower() for word in ['mean', 'std', 'correlation']):
            discoveries['statistical_analysis'] = observation.split('\n')[:10]

        if discoveries:
            current_questions = context.get('knowledge_gaps', [])
            updated_questions = []
            for question in current_questions:
                if not any(keyword in observation.lower() for keyword in question.lower().split()):
                    updated_questions.append(question)
            discoveries['updated_questions'] = updated_questions

        return discoveries

    def _evaluate_iteration_quality(self, discoveries: Dict, observation: str) -> float:
        """Agent evaluates quality of its own iteration."""
        quality_score = 0.0

        if discoveries:
            quality_score += len(discoveries) * 0.2

        lines = observation.split('\n')
        meaningful_lines = [l for l in lines if l.strip() and 'error' not in l.lower()]
        quality_score += min(len(meaningful_lines) * 0.1, 0.5)

        if 'ERROR' in observation:
            quality_score -= 0.3

        if len(discoveries) > 2:
            quality_score += 0.2

        return max(0.0, min(1.0, quality_score))

    def _update_knowledge_base(self, result: ExplorationResult):
        """Update agent's knowledge base with new discoveries."""
        for key, value in result.discoveries.items():
            if key == 'updated_questions':
                self.knowledge_base['open_questions'] = value
            else:
                self.knowledge_base['discoveries'][key] = value

        if result.success and result.quality_score > 0.5:
            pattern = {
                'approach': result.thought[:100],
                'action_type': self._classify_action(result.action),
                'quality': result.quality_score
            }
            self.successful_patterns.append(pattern)

    def _classify_action(self, action_code: str) -> str:
        """Classify the type of action for pattern learning."""
        if 'columns' in action_code.lower():
            return 'schema_discovery'
        elif 'corr' in action_code.lower():
            return 'correlation_analysis'
        elif 'describe' in action_code.lower():
            return 'statistical_summary'
        elif 'plot' in action_code.lower() or 'hist' in action_code.lower():
            return 'visualization'
        else:
            return 'general_analysis'

    async def _assess_exploration_progress(self) -> Dict[str, Any]:
        """Agent assesses its own exploration progress."""
        total_discoveries = len(self.knowledge_base.get('discoveries', {}))
        open_questions = len(self.knowledge_base.get('open_questions', []))

        completion_percentage = min(total_discoveries * 20, 80)
        if open_questions <= 2:
            completion_percentage += 20

        should_stop = completion_percentage >= 85 or self.iteration_count >= 15

        return {
            'completion_percentage': completion_percentage,
            'total_discoveries': total_discoveries,
            'open_questions': open_questions,
            'should_stop': should_stop
        }

    async def _assess_overall_quality(self) -> float:
        """Agent assesses overall quality of its exploration."""
        if not self.exploration_history:
            return 0.0

        avg_quality = sum(r.quality_score for r in self.exploration_history) / len(self.exploration_history)
        success_rate = sum(1 for r in self.exploration_history if r.success) / len(self.exploration_history)

        return (avg_quality + success_rate) / 2

    def _parse_thought_action(self, response: str) -> Tuple[str, str]:
        """Parse agent's response into thought and action components."""
        lines = response.split('\n')
        thought = ""
        action = ""

        capturing_action = False

        for line in lines:
            if line.strip().startswith('```python') or 'ACTION:' in line.upper():
                capturing_action = True
                continue
            elif line.strip() == '```' and capturing_action:
                break
            elif capturing_action:
                action += line + '\n'
            elif not capturing_action and line.strip():
                thought += line + ' '

        if not action.strip():
            action = response

        return thought.strip(), action.strip()

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM with autonomous prompt."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))

        except Exception as e:
            # Fallback for testing
            return f"""
I need to understand the dataset structure and patterns.

```python
print("Dataset columns:", dataset.columns.tolist())
print("Data shape:", dataset.shape)
print("Data types:")
print(dataset.dtypes)
print("\\nFirst 3 rows:")
print(dataset.head(3))
print("\\nBasic statistics:")
print(dataset.describe())
```
"""

    async def _autonomous_recovery(self, error: str) -> Dict[str, Any]:
        """Agent autonomously recovers from errors."""
        recovery_prompt = get_autonomous_recovery_prompt(
            {'error': error, 'iteration': self.iteration_count},
            {'exploration_history': self.exploration_history}
        )

        response = await self._query_llm(recovery_prompt)
        can_continue = 'continue' in response.lower() and self.iteration_count < self.max_iterations

        return {
            'can_continue': can_continue,
            'recovery_strategy': response,
            'adjusted_approach': 'retry_with_different_method'
        }


class ParallelExperimentExecutor:
    """Executes multiple autonomous experiments in parallel."""

    def __init__(self, llm, execution_context, max_workers: int = 4):
        self.llm = llm
        self.execution_context = execution_context
        self.max_workers = max_workers
        self.experiment_history = []

    async def execute_experiments_parallel(self, hypotheses: List[Hypothesis]) -> List[Dict[str, Any]]:
        """Execute multiple experiments in parallel."""
        print(f"[START] Running {len(hypotheses)} experiments in parallel...")

        experiment_designs = []
        for hypothesis in hypotheses:
            design = await self._design_experiment_autonomous(hypothesis)
            experiment_designs.append((hypothesis, design))

        with concurrent.futures.ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            future_to_experiment = {
                executor.submit(self._run_single_experiment, hypothesis, design): (hypothesis, design)
                for hypothesis, design in experiment_designs
            }

            results = []
            for future in concurrent.futures.as_completed(future_to_experiment):
                hypothesis, design = future_to_experiment[future]
                try:
                    result = future.result()
                    result['hypothesis'] = hypothesis
                    result['design'] = design
                    results.append(result)
                    print(f"[SUCCESS] Experiment completed: {hypothesis.id}")
                except Exception as e:
                    print(f"[ERROR] Experiment failed: {hypothesis.id} - {e}")
                    results.append({
                        'hypothesis': hypothesis,
                        'design': design,
                        'success': False,
                        'error': str(e)
                    })

        self.experiment_history.extend(results)
        return results

    async def _design_experiment_autonomous(self, hypothesis: Hypothesis) -> Experiment:
        """Agent autonomously designs experiment for hypothesis."""
        available_algorithms = [
            'KMeans', 'GaussianMixture', 'DBSCAN', 'AgglomerativeClustering',
            'SpectralClustering', 'Birch', 'MeanShift'
        ]

        design_prompt = get_autonomous_experiment_prompt(
            hypothesis.description,
            available_algorithms,
            {'hypothesis_confidence': hypothesis.confidence}
        )

        response = await self._query_llm(design_prompt)
        algorithm = self._extract_algorithm_choice(response, available_algorithms)
        parameters = self._extract_parameters(response)

        return Experiment(
            hypothesis_id=hypothesis.id,
            algorithm=algorithm,
            parameters=parameters,
            success_metrics=['silhouette_score', 'calinski_harabasz_score'],
            expected_outcomes=self._extract_expected_outcomes(response)
        )

    def _run_single_experiment(self, hypothesis: Hypothesis, experiment: Experiment) -> Dict[str, Any]:
        """Run a single experiment synchronously."""
        try:
            dataset = self.execution_context.get('dataset')
            if dataset is None:
                raise ValueError("Dataset not available in execution context")

            numeric_cols = dataset.select_dtypes(include=[np.number]).columns
            X = dataset[numeric_cols].values

            if len(X) == 0:
                raise ValueError("No numeric data available")

            from sklearn.preprocessing import StandardScaler
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)

            algorithm_name = experiment.algorithm
            params = experiment.parameters

            if algorithm_name == 'KMeans':
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=params.get('n_clusters', 3), random_state=42)
            elif algorithm_name == 'GaussianMixture':
                from sklearn.mixture import GaussianMixture
                model = GaussianMixture(n_components=params.get('n_components', 3), random_state=42)
            elif algorithm_name == 'DBSCAN':
                from sklearn.cluster import DBSCAN
                model = DBSCAN(eps=params.get('eps', 0.5), min_samples=params.get('min_samples', 5))
            else:
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=3, random_state=42)

            labels = model.fit_predict(X_scaled)
            n_clusters = len(np.unique(labels))

            if n_clusters > 1:
                from sklearn.metrics import silhouette_score, calinski_harabasz_index
                silhouette = silhouette_score(X_scaled, labels)
                calinski_harabasz = calinski_harabasz_index(X_scaled, labels)
            else:
                silhouette = -1.0
                calinski_harabasz = 0.0

            return {
                'success': True,
                'algorithm': algorithm_name,
                'parameters': params,
                'n_clusters': n_clusters,
                'silhouette_score': silhouette,
                'calinski_harabasz_score': calinski_harabasz,
                'labels': labels,
                'model': model
            }

        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'algorithm': experiment.algorithm,
                'parameters': experiment.parameters
            }

    def _extract_algorithm_choice(self, response: str, available: List[str]) -> str:
        """Extract algorithm choice from agent response."""
        response_lower = response.lower()
        for algorithm in available:
            if algorithm.lower() in response_lower:
                return algorithm
        return 'KMeans'

    def _extract_parameters(self, response: str) -> Dict[str, Any]:
        """Extract parameters from agent response."""
        params = {}

        if 'clusters' in response.lower():
            import re
            cluster_match = re.search(r'(\d+)\s*cluster', response.lower())
            if cluster_match:
                params['n_clusters'] = int(cluster_match.group(1))
                params['n_components'] = int(cluster_match.group(1))

        if 'eps' in response.lower():
            eps_match = re.search(r'eps[=:\s]+([0-9.]+)', response.lower())
            if eps_match:
                params['eps'] = float(eps_match.group(1))

        if not params:
            params = {'n_clusters': 3, 'n_components': 3}

        return params

    def _extract_expected_outcomes(self, response: str) -> Dict[str, Any]:
        """Extract expected outcomes from agent response."""
        return {
            'expected_quality': 'high' if 'good' in response.lower() else 'medium',
            'rationale': response[:200] + '...' if len(response) > 200 else response
        }

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM for experiment design."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))
        except Exception as e:
            return f"Algorithm: KMeans, Parameters: n_clusters=3, Expected: Good clustering"


class AutonomousValidationSystem:
    """Self-validation system that learns from validation results."""

    def __init__(self, validation_boundaries):
        self.validation_boundaries = validation_boundaries
        self.validation_history = []
        self.learned_patterns = []
        self.failure_recovery_strategies = []

    async def autonomous_validate(self, results: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Agent autonomously validates results against learned patterns."""
        print(f"[VALIDATE] Autonomous validation in progress...")

        boundary_validation = self._validate_boundaries(results)
        pattern_validation = await self._validate_against_patterns(results, context)
        self_assessment = await self._agent_self_assessment(results, context)

        overall_validation = {
            'boundary_validation': boundary_validation,
            'pattern_validation': pattern_validation,
            'self_assessment': self_assessment,
            'overall_passed': (
                boundary_validation.get('passed', False) and
                pattern_validation.get('passed', False) and
                self_assessment.get('confidence', 0) > 0.7
            )
        }

        self._learn_from_validation(overall_validation, results, context)
        print(f"[SUCCESS] Validation complete: {'PASSED' if overall_validation['overall_passed'] else 'FAILED'}")

        return overall_validation

    def _validate_boundaries(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """Validate against defined boundaries."""
        validation = {'passed': True, 'violations': []}

        for boundary_name, threshold in self.validation_boundaries.items():
            if boundary_name in results:
                current_value = results[boundary_name]
                if isinstance(threshold, (int, float)):
                    if current_value < threshold:
                        validation['passed'] = False
                        validation['violations'].append({
                            'boundary': boundary_name,
                            'required': threshold,
                            'actual': current_value
                        })

        return validation

    async def _validate_against_patterns(self, results: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Validate against learned successful patterns."""
        if not self.learned_patterns:
            return {'passed': True, 'reason': 'No learned patterns yet'}

        pattern_scores = []
        for pattern in self.learned_patterns[-5:]:
            score = self._calculate_pattern_similarity(results, pattern)
            pattern_scores.append(score)

        avg_pattern_score = sum(pattern_scores) / len(pattern_scores) if pattern_scores else 0

        return {
            'passed': avg_pattern_score > 0.6,
            'pattern_similarity': avg_pattern_score,
            'matching_patterns': len([s for s in pattern_scores if s > 0.7])
        }

    async def _agent_self_assessment(self, results: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Agent assesses its own results quality."""
        return {
            'confidence': 0.8,
            'assessment': 'Autonomous self-assessment',
            'concerns': []
        }

    def _calculate_pattern_similarity(self, current_results: Dict[str, Any], pattern: Dict[str, Any]) -> float:
        """Calculate similarity between current results and learned pattern."""
        similarity = 0.0
        comparisons = 0

        for key in ['silhouette_score', 'n_clusters', 'algorithm']:
            if key in current_results and key in pattern:
                if key == 'algorithm':
                    similarity += 1.0 if current_results[key] == pattern[key] else 0.0
                else:
                    diff = abs(current_results[key] - pattern[key])
                    max_val = max(current_results[key], pattern[key])
                    if max_val > 0:
                        similarity += max(0, 1 - (diff / max_val))
                comparisons += 1

        return similarity / comparisons if comparisons > 0 else 0.0

    def _learn_from_validation(self, validation_result: Dict[str, Any], results: Dict[str, Any], context: Dict[str, Any]):
        """Learn patterns from validation results."""
        validation_record = {
            'validation_result': validation_result,
            'results': results,
            'context': context,
            'timestamp': time.time()
        }
        self.validation_history.append(validation_record)

        if validation_result.get('overall_passed'):
            pattern = {
                'algorithm': results.get('algorithm'),
                'silhouette_score': results.get('silhouette_score', 0),
                'n_clusters': results.get('n_clusters', 0),
                'parameters': results.get('parameters', {}),
                'context_features': {
                    'data_size': context.get('data_size', 0),
                    'n_features': context.get('n_features', 0)
                }
            }
            self.learned_patterns.append(pattern)

        if len(self.validation_history) > 100:
            self.validation_history = self.validation_history[-50:]

        if len(self.learned_patterns) > 50:
            self.learned_patterns = self.learned_patterns[-25:]


class AutonomousStrategySynthesizer:
    """Synthesizes optimal sampling strategy from all autonomous discoveries."""

    def __init__(self, llm):
        self.llm = llm
        self.synthesis_history = []

    async def autonomous_synthesize(self, exploration_results: List[Dict], experiment_results: List[Dict], validation_results: Dict) -> Dict[str, Any]:
        """Agent autonomously synthesizes optimal strategy from all learnings."""
        print(f"[SYNTHESIS] Autonomous strategy synthesis...")

        synthesis_context = {
            'exploration_discoveries': len(exploration_results),
            'experiment_results': experiment_results,
            'validation_learnings': validation_results,
            'top_performers': self._identify_top_performers(experiment_results),
            'learned_patterns': self._extract_learned_patterns(exploration_results, experiment_results)
        }

        strategy_response = await self._query_llm("Generate optimal sampling strategy based on experimental evidence")
        final_strategy = self._parse_strategy_response(strategy_response, experiment_results)
        strategy_validation = await self._validate_strategy(final_strategy, synthesis_context)

        if not strategy_validation.get('acceptable', False):
            print(f"[TARGET] Agent refining strategy...")
            final_strategy = await self._refine_strategy(final_strategy, strategy_validation)

        self.synthesis_history.append({
            'strategy': final_strategy,
            'context': synthesis_context,
            'validation': strategy_validation
        })

        print(f"[SUCCESS] Strategy synthesis complete: {final_strategy.get('algorithm', 'unknown')}")
        return final_strategy

    def _identify_top_performers(self, experiment_results: List[Dict]) -> List[Dict]:
        """Identify best performing experiments."""
        valid_results = [r for r in experiment_results if r.get('success', False)]
        if not valid_results:
            return []

        sorted_results = sorted(
            valid_results,
            key=lambda x: x.get('silhouette_score', -1),
            reverse=True
        )

        return sorted_results[:3]

    def _extract_learned_patterns(self, exploration_results: List[Dict], experiment_results: List[Dict]) -> List[Dict]:
        """Extract patterns from all results."""
        patterns = []

        algorithm_performance = defaultdict(list)
        for result in experiment_results:
            if result.get('success'):
                algorithm = result.get('algorithm', 'unknown')
                score = result.get('silhouette_score', 0)
                algorithm_performance[algorithm].append(score)

        for algorithm, scores in algorithm_performance.items():
            if scores:
                patterns.append({
                    'type': 'algorithm_performance',
                    'algorithm': algorithm,
                    'avg_score': sum(scores) / len(scores),
                    'success_rate': len(scores) / len([r for r in experiment_results if r.get('algorithm') == algorithm])
                })

        return patterns

    def _parse_strategy_response(self, response: str, experiment_results: List[Dict]) -> Dict[str, Any]:
        """Parse agent's strategy response into structured format."""
        strategy = {
            'algorithm': 'KMeans',
            'parameters': {},
            'rationale': response,
            'confidence': 0.8
        }

        response_lower = response.lower()
        algorithms = ['kmeans', 'gaussianmixture', 'dbscan', 'spectral', 'hierarchical']
        for alg in algorithms:
            if alg in response_lower:
                strategy['algorithm'] = alg.title()
                break

        import re
        cluster_match = re.search(r'(\d+)\s*cluster', response_lower)
        if cluster_match:
            strategy['parameters']['n_clusters'] = int(cluster_match.group(1))

        if not strategy['parameters'] and experiment_results:
            top_result = max(experiment_results, key=lambda x: x.get('silhouette_score', -1), default={})
            if top_result.get('success'):
                strategy['algorithm'] = top_result.get('algorithm', 'KMeans')
                strategy['parameters'] = top_result.get('parameters', {})

        return strategy

    async def _validate_strategy(self, strategy: Dict[str, Any], context: Dict[str, Any]) -> Dict[str, Any]:
        """Agent validates its synthesized strategy."""
        validation_checks = []

        if strategy.get('algorithm') == 'DBSCAN' and context.get('data_size', 0) > 10000:
            validation_checks.append('DBSCAN may be slow on large dataset')

        n_clusters = strategy.get('parameters', {}).get('n_clusters', 0)
        data_size = context.get('data_size', 0)
        if n_clusters > data_size / 10:
            validation_checks.append('Too many clusters for data size')

        acceptable = len(validation_checks) == 0

        return {
            'acceptable': acceptable,
            'issues': validation_checks,
            'confidence': 0.9 if acceptable else 0.4
        }

    async def _refine_strategy(self, strategy: Dict[str, Any], validation: Dict[str, Any]) -> Dict[str, Any]:
        """Agent refines strategy based on validation issues."""
        issues = validation.get('issues', [])
        refined_strategy = strategy.copy()

        for issue in issues:
            if 'too many clusters' in issue.lower():
                current_clusters = refined_strategy.get('parameters', {}).get('n_clusters', 3)
                refined_strategy['parameters']['n_clusters'] = max(2, current_clusters // 2)

            if 'dbscan' in issue.lower() and 'slow' in issue.lower():
                refined_strategy['algorithm'] = 'KMeans'
                refined_strategy['parameters'] = {'n_clusters': 3}

        refined_strategy['refinement_applied'] = issues
        return refined_strategy

    async def _query_llm(self, prompt: str) -> str:
        """Query LLM for strategy synthesis."""
        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": prompt})
                if hasattr(response, 'content'):
                    return response.content
                else:
                    return str(response)
            else:
                return str(self.llm.invoke(prompt))
        except Exception as e:
            return f"Final strategy: Use KMeans with 3 clusters based on experimental evidence"


class TimingDataSelectionAgent:
    """
    Completely Autonomous Timing Data Selection Agent.
    Features autonomous exploration, parallel experimentation, self-validation, and strategy synthesis.
    """

    def __init__(self, llm, verbose: bool = True):
        """Initialize the autonomous agent."""
        self.llm = llm
        self.verbose = verbose
        self.conversation_history = []
        self.current_data = None
        self.reasoning_log = []
        self._imports_loaded = False

        # Execution Engine
        self.execution_context = {}
        self.initialize_execution_context()

        # Autonomous Components
        self.exploration_engine = AutonomousExplorationEngine(llm, self.execution_context)
        self.experiment_executor = ParallelExperimentExecutor(llm, self.execution_context)
        self.validation_system = AutonomousValidationSystem(VALIDATION_BOUNDARIES)
        self.strategy_synthesizer = AutonomousStrategySynthesizer(llm)

        # Configuration
        self.agentic_mode = True
        self.validation_boundaries = VALIDATION_BOUNDARIES
        self.iteration_triggers = ITERATION_TRIGGERS
        self.iteration_count = 0
        self.max_iterations = 50
        self.system_prompt = TIMING_SYSTEM_PROMPT

        print("[AGENT] Autonomous Agent Initialized")
        print("[AGENT] Exploration Engine: Ready")
        print("[AGENT] Parallel Executor: Ready")
        print("[AGENT] Validation System: Ready")
        print("[AGENT] Strategy Synthesizer: Ready")

    def initialize_execution_context(self):
        """Initialize execution context."""
        import io
        import sys

        self.execution_context = {
            'pd': pd,
            'np': np,
            'io': io,
            'sys': sys,
            'dataset': None,
            '_stdout_capture': None,
            '_stderr_capture': None
        }

        if SKLEARN_AVAILABLE:
            from sklearn.preprocessing import StandardScaler
            from sklearn.cluster import KMeans
            from sklearn.mixture import GaussianMixture
            self.execution_context.update({
                'StandardScaler': StandardScaler,
                'KMeans': KMeans,
                'GaussianMixture': GaussianMixture
            })

    async def autonomous_sample_selection(self, csv_path: str, target_percentage: float = 5.0) -> Dict[str, Any]:
        """
        Main autonomous sampling pipeline.
        Agent explores, experiments, validates, and synthesizes strategy independently.
        """
        print(f"\n[START] AUTONOMOUS SAMPLING PIPELINE INITIATED")
        print(f"[DATA] Target: {target_percentage}% of samples")
        print(f"[TARGET] Mode: Fully autonomous with {self.exploration_engine.max_iterations} max exploration iterations")

        # Load dataset
        self.current_data = pd.read_csv(csv_path)
        self.execution_context['dataset'] = self.current_data
        self.execution_context['current_data'] = self.current_data

        print(f"[FILE] Dataset loaded: {len(self.current_data)} samples")

        try:
            # Phase 1: Autonomous Exploration
            print(f"\n[VALIDATE] PHASE 1: AUTONOMOUS EXPLORATION")
            exploration_results = await self.exploration_engine.autonomous_explore(
                self.current_data,
                target_percentage
            )

            # Phase 2: Autonomous Hypothesis Generation
            print(f"\n[HYPOTHESIS] PHASE 2: AUTONOMOUS HYPOTHESIS GENERATION")
            hypotheses = await self._generate_autonomous_hypotheses(exploration_results)

            # Phase 3: Parallel Autonomous Experimentation
            print(f"\n[EXPERIMENT] PHASE 3: PARALLEL AUTONOMOUS EXPERIMENTATION")
            experiment_results = await self.experiment_executor.execute_experiments_parallel(hypotheses)

            # Phase 4: Autonomous Validation
            print(f"\n[VALIDATE] PHASE 4: AUTONOMOUS VALIDATION")
            validation_results = {}
            for result in experiment_results:
                if result.get('success'):
                    validation = await self.validation_system.autonomous_validate(
                        result,
                        {'data_size': len(self.current_data), 'target_percentage': target_percentage}
                    )
                    validation_results[result.get('algorithm', 'unknown')] = validation

            # Phase 5: Autonomous Strategy Synthesis
            print(f"\n[SYNTHESIS] PHASE 5: AUTONOMOUS STRATEGY SYNTHESIS")
            final_strategy = await self.strategy_synthesizer.autonomous_synthesize(
                exploration_results.get('exploration_results', []),
                experiment_results,
                validation_results
            )

            # Phase 6: Execute Final Sampling
            print(f"\n[TARGET] PHASE 6: AUTONOMOUS SAMPLE EXECUTION")
            selected_indices = await self._execute_autonomous_sampling(final_strategy, target_percentage)

            # Phase 7: Quality Assessment
            print(f"\n[PROGRESS] PHASE 7: AUTONOMOUS QUALITY ASSESSMENT")
            quality_assessment = await self._autonomous_quality_assessment(
                selected_indices, final_strategy, exploration_results, experiment_results
            )

            print(f"\n[COMPLETE] AUTONOMOUS PIPELINE COMPLETE")
            print(f"[SUCCESS] Selected {len(selected_indices)} samples using {final_strategy.get('algorithm', 'unknown')} strategy")
            print(f"[DATA] Quality Score: {quality_assessment.get('overall_quality', 0):.3f}")

            return {
                'selected_indices': selected_indices,
                'final_strategy': final_strategy,
                'exploration_results': exploration_results,
                'experiment_results': experiment_results,
                'validation_results': validation_results,
                'quality_assessment': quality_assessment,
                'autonomous_pipeline_stats': {
                    'total_exploration_iterations': exploration_results.get('total_iterations', 0),
                    'experiments_run': len(experiment_results),
                    'validations_passed': sum(1 for v in validation_results.values() if v.get('overall_passed', False)),
                    'final_algorithm': final_strategy.get('algorithm', 'unknown'),
                    'pipeline_quality': quality_assessment.get('overall_quality', 0)
                }
            }

        except Exception as e:
            print(f"[ERROR] Autonomous pipeline error: {e}")
            recovery = await self.exploration_engine._autonomous_recovery(str(e))
            return {
                'error': str(e),
                'recovery_attempted': True,
                'recovery_strategy': recovery,
                'selected_indices': []
            }

    async def _generate_autonomous_hypotheses(self, exploration_results: Dict[str, Any]) -> List[Hypothesis]:
        """Agent autonomously generates hypotheses from exploration discoveries."""
        knowledge_base = exploration_results.get('knowledge_base', {})
        discoveries = knowledge_base.get('discoveries', {})

        hypothesis_prompt = get_autonomous_hypothesis_prompt(
            discoveries,
            {'exploration_quality': exploration_results.get('exploration_quality', 0)}
        )

        try:
            if hasattr(self.llm, 'invoke'):
                response = self.llm.invoke({"input": hypothesis_prompt})
                if hasattr(response, 'content'):
                    hypothesis_text = response.content
                else:
                    hypothesis_text = str(response)
            else:
                hypothesis_text = str(self.llm.invoke(hypothesis_prompt))

            hypotheses = self._parse_hypotheses_from_response(hypothesis_text)
            print(f"[HYPOTHESIS] Generated {len(hypotheses)} autonomous hypotheses")
            for i, h in enumerate(hypotheses):
                print(f"   {i+1}. {h.description[:60]}...")

            return hypotheses

        except Exception as e:
            print(f"[WARNING] Hypothesis generation error: {e}")
            return self._get_default_hypotheses()

    def _parse_hypotheses_from_response(self, response: str) -> List[Hypothesis]:
        """Parse structured hypotheses from agent response."""
        hypotheses = []
        lines = response.split('\n')

        current_hypothesis = {}
        hypothesis_count = 0

        for line in lines:
            line = line.strip()
            if line.startswith('HYPOTHESIS'):
                if current_hypothesis:
                    hypotheses.append(self._create_hypothesis_from_dict(current_hypothesis, hypothesis_count))
                    hypothesis_count += 1
                current_hypothesis = {'description': line.replace('HYPOTHESIS', '').strip(':').strip()}
            elif line.startswith('PREDICTION:'):
                current_hypothesis['prediction'] = line.replace('PREDICTION:', '').strip()
            elif line.startswith('TEST:'):
                current_hypothesis['test_method'] = line.replace('TEST:', '').strip()

        if current_hypothesis:
            hypotheses.append(self._create_hypothesis_from_dict(current_hypothesis, hypothesis_count))

        if not hypotheses:
            return self._get_default_hypotheses()

        return hypotheses[:5]

    def _create_hypothesis_from_dict(self, hyp_dict: Dict, count: int) -> Hypothesis:
        """Create Hypothesis object from parsed dictionary."""
        return Hypothesis(
            id=f"hyp_{count}",
            description=hyp_dict.get('description', f'Hypothesis {count}'),
            prediction=hyp_dict.get('prediction', 'Unknown prediction'),
            test_method=hyp_dict.get('test_method', 'Algorithm comparison'),
            confidence=0.8,
            rationale=f"Generated from autonomous exploration {count}"
        )

    def _get_default_hypotheses(self) -> List[Hypothesis]:
        """Generate default hypotheses if parsing fails."""
        return [
            Hypothesis(
                id="hyp_default_1",
                description="KMeans clustering will provide good sample diversity",
                prediction="Silhouette score > 0.4",
                test_method="Run KMeans with different cluster counts",
                confidence=0.7,
                rationale="Default hypothesis - KMeans is reliable"
            ),
            Hypothesis(
                id="hyp_default_2",
                description="Gaussian Mixture will handle overlapping distributions",
                prediction="Better than KMeans if data has overlapping clusters",
                test_method="Compare GMM vs KMeans performance",
                confidence=0.6,
                rationale="Default hypothesis - GMM handles overlap"
            ),
            Hypothesis(
                id="hyp_default_3",
                description="DBSCAN will find natural density clusters",
                prediction="Good clustering if natural dense regions exist",
                test_method="Test DBSCAN with adaptive epsilon",
                confidence=0.5,
                rationale="Default hypothesis - DBSCAN finds natural clusters"
            )
        ]

    async def _execute_autonomous_sampling(self, strategy: Dict[str, Any], target_percentage: float) -> List[int]:
        """Execute final sampling using autonomous strategy."""
        algorithm = strategy.get('algorithm', 'KMeans')
        parameters = strategy.get('parameters', {})

        try:
            numeric_cols = self.current_data.select_dtypes(include=[np.number]).columns
            X = self.current_data[numeric_cols].values

            if len(X) == 0:
                print("[WARNING] No numeric data available, using random sampling")
                n_samples = int(len(self.current_data) * target_percentage / 100)
                return np.random.choice(len(self.current_data), size=n_samples, replace=False).tolist()

            from sklearn.preprocessing import StandardScaler
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X)

            if algorithm == 'KMeans':
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=parameters.get('n_clusters', 3), random_state=42)
            elif algorithm == 'GaussianMixture':
                from sklearn.mixture import GaussianMixture
                model = GaussianMixture(n_components=parameters.get('n_components', 3), random_state=42)
            elif algorithm == 'DBSCAN':
                from sklearn.cluster import DBSCAN
                model = DBSCAN(eps=parameters.get('eps', 0.5), min_samples=parameters.get('min_samples', 5))
            else:
                from sklearn.cluster import KMeans
                model = KMeans(n_clusters=3, random_state=42)

            labels = model.fit_predict(X_scaled)
            selected_indices = self._uncertainty_sampling_from_clusters(X_scaled, labels, target_percentage)

            print(f"[TARGET] Selected {len(selected_indices)} samples using autonomous {algorithm} strategy")
            return selected_indices

        except Exception as e:
            print(f"[WARNING] Sampling execution error: {e}, falling back to random sampling")
            n_samples = int(len(self.current_data) * target_percentage / 100)
            return np.random.choice(len(self.current_data), size=n_samples, replace=False).tolist()

    def _uncertainty_sampling_from_clusters(self, X_scaled: np.ndarray, labels: np.ndarray, target_percentage: float) -> List[int]:
        """Apply uncertainty sampling within each cluster."""
        n_target = int(len(X_scaled) * target_percentage / 100)
        unique_labels = np.unique(labels)
        if -1 in unique_labels:
            unique_labels = unique_labels[unique_labels != -1]

        if len(unique_labels) == 0:
            return np.random.choice(len(X_scaled), size=n_target, replace=False).tolist()

        selected_indices = []
        samples_per_cluster = max(1, n_target // len(unique_labels))

        for cluster_id in unique_labels:
            cluster_mask = labels == cluster_id
            cluster_indices = np.where(cluster_mask)[0]

            if len(cluster_indices) == 0:
                continue

            cluster_data = X_scaled[cluster_mask]
            centroid = np.mean(cluster_data, axis=0)
            distances = np.linalg.norm(cluster_data - centroid, axis=1)

            n_select = min(samples_per_cluster, len(cluster_indices))
            uncertain_indices = np.argsort(distances)[-n_select:]
            selected_cluster_indices = cluster_indices[uncertain_indices]

            selected_indices.extend(selected_cluster_indices.tolist())

        while len(selected_indices) < n_target:
            remaining_indices = [i for i in range(len(X_scaled)) if i not in selected_indices]
            if not remaining_indices:
                break
            selected_indices.append(np.random.choice(remaining_indices))

        return selected_indices[:n_target]

    async def _autonomous_quality_assessment(self, selected_indices: List[int], strategy: Dict[str, Any],
                                           exploration_results: Dict, experiment_results: List[Dict]) -> Dict[str, Any]:
        """Agent autonomously assesses the quality of its sampling results."""
        assessment = {
            'overall_quality': 0.0,
            'coverage_quality': 0.0,
            'diversity_quality': 0.0,
            'strategy_confidence': strategy.get('confidence', 0.5),
            'exploration_quality': exploration_results.get('exploration_quality', 0.0)
        }

        try:
            if len(selected_indices) > 0:
                numeric_cols = self.current_data.select_dtypes(include=[np.number]).columns
                if len(numeric_cols) > 0:
                    all_data = self.current_data[numeric_cols].values
                    selected_data = all_data[selected_indices]

                    coverage_scores = []
                    for i in range(all_data.shape[1]):
                        full_range = np.max(all_data[:, i]) - np.min(all_data[:, i])
                        selected_range = np.max(selected_data[:, i]) - np.min(selected_data[:, i])
                        if full_range > 0:
                            coverage_scores.append(selected_range / full_range)

                    assessment['coverage_quality'] = np.mean(coverage_scores) if coverage_scores else 0.0

            strategy_algorithm = strategy.get('algorithm', 'unknown')
            strategy_performance = 0.0

            for result in experiment_results:
                if result.get('algorithm') == strategy_algorithm and result.get('success'):
                    strategy_performance = max(strategy_performance, result.get('silhouette_score', 0.0))

            assessment['strategy_performance'] = strategy_performance

            assessment['overall_quality'] = (
                assessment['coverage_quality'] * 0.3 +
                assessment['strategy_performance'] * 0.4 +
                assessment['strategy_confidence'] * 0.3
            )

            print(f"[DATA] Quality Assessment:")
            print(f"   Coverage: {assessment['coverage_quality']:.3f}")
            print(f"   Strategy Performance: {assessment['strategy_performance']:.3f}")
            print(f"   Strategy Confidence: {assessment['strategy_confidence']:.3f}")
            print(f"   Overall Quality: {assessment['overall_quality']:.3f}")

        except Exception as e:
            print(f"[WARNING] Quality assessment error: {e}")
            assessment['error'] = str(e)

        return assessment


# LLM Connection Configuration
def initialize_ollama_llm(model_name: str = "llama2", base_url: str = "http://localhost:11434"):
    """Initialize Ollama LLM connection."""
    try:
        from langchain_community.llms import Ollama
        llm = Ollama(
            model=model_name,
            base_url=base_url,
            temperature=0.1,
            top_p=0.9,
            num_predict=2048
        )
        return llm
    except ImportError:
        print("[WARNING] langchain_community not available for Ollama")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to initialize Ollama: {e}")
        return None


def initialize_openai_llm(api_key: Optional[str] = None, model: str = "gpt-3.5-turbo"):
    """Initialize OpenAI LLM connection."""
    try:
        from langchain_openai import ChatOpenAI
        api_key = api_key or os.getenv('OPENAI_API_KEY')
        if not api_key:
            print("[WARNING] OpenAI API key not found")
            return None

        llm = ChatOpenAI(
            openai_api_key=api_key,
            model=model,
            temperature=0.1,
            max_tokens=2048
        )
        return llm
    except ImportError:
        print("[WARNING] langchain_openai not available")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to initialize OpenAI: {e}")
        return None


def initialize_anthropic_llm(api_key: Optional[str] = None, model: str = "claude-3-sonnet-20240229"):
    """Initialize Anthropic Claude LLM connection."""
    try:
        from langchain_anthropic import ChatAnthropic
        api_key = api_key or os.getenv('ANTHROPIC_API_KEY')
        if not api_key:
            print("[WARNING] Anthropic API key not found")
            return None

        llm = ChatAnthropic(
            anthropic_api_key=api_key,
            model=model,
            temperature=0.1,
            max_tokens=2048
        )
        return llm
    except ImportError:
        print("[WARNING] langchain_anthropic not available")
        return None
    except Exception as e:
        print(f"[ERROR] Failed to initialize Anthropic: {e}")
        return None


def test_llm_connection(llm):
    """Test LLM connection with simple query."""
    if not llm:
        return False

    try:
        test_prompt = "Hello, respond with 'Connection successful'"
        if hasattr(llm, 'invoke'):
            response = llm.invoke({"input": test_prompt})
            if hasattr(response, 'content'):
                result = response.content
            else:
                result = str(response)
        else:
            result = str(llm.invoke(test_prompt))

        print(f"[CONNECTION] LLM test response: {result[:50]}...")
        return True

    except Exception as e:
        print(f"[ERROR] LLM connection test failed: {e}")
        return False


def auto_initialize_llm():
    """Automatically initialize the best available LLM."""
    print("[INIT] Auto-initializing LLM connection...")

    # Try Ollama first (local, no API key needed)
    llm = initialize_ollama_llm()
    if llm and test_llm_connection(llm):
        print("[SUCCESS] Connected to Ollama LLM")
        return llm

    # Try OpenAI
    llm = initialize_openai_llm()
    if llm and test_llm_connection(llm):
        print("[SUCCESS] Connected to OpenAI LLM")
        return llm

    # Try Anthropic
    llm = initialize_anthropic_llm()
    if llm and test_llm_connection(llm):
        print("[SUCCESS] Connected to Anthropic LLM")
        return llm

    print("[ERROR] No LLM connection available")
    return None


def create_autonomous_agent(llm=None, verbose: bool = True):
    """Factory function to create autonomous agent with LLM connection."""
    if llm is None:
        llm = auto_initialize_llm()

    if llm is None:
        print("[ERROR] Cannot create agent without LLM connection")
        print("[INFO] Please ensure you have:")
        print("   - Ollama running locally (http://localhost:11434), or")
        print("   - OPENAI_API_KEY environment variable set, or")
        print("   - ANTHROPIC_API_KEY environment variable set")
        return None

    agent = TimingDataSelectionAgent(llm, verbose=verbose)
    print(f"[SUCCESS] Autonomous agent created successfully")
    return agent


# Usage Example
if __name__ == "__main__":
    import asyncio

    async def main():
        """Example usage of autonomous timing data selection agent."""
        # Create agent with auto-initialized LLM
        agent = create_autonomous_agent(verbose=True)

        if agent is None:
            print("[ERROR] Failed to create agent")
            return

        # Example CSV path (replace with your actual CSV file)
        csv_path = "timing_data.csv"
        target_percentage = 5.0  # Select 5% of samples

        print(f"\n[START] Running autonomous sample selection on {csv_path}")
        print(f"[TARGET] Selecting {target_percentage}% of samples autonomously")

        try:
            # Run autonomous pipeline
            results = await agent.autonomous_sample_selection(csv_path, target_percentage)

            if 'error' in results:
                print(f"[ERROR] Pipeline failed: {results['error']}")
            else:
                print(f"\n[RESULTS] Autonomous pipeline completed successfully!")
                print(f"   Selected Indices: {len(results['selected_indices'])} samples")
                print(f"   Algorithm Used: {results['final_strategy'].get('algorithm', 'unknown')}")
                print(f"   Quality Score: {results['quality_assessment'].get('overall_quality', 0):.3f}")
                print(f"   Exploration Iterations: {results['autonomous_pipeline_stats']['total_exploration_iterations']}")
                print(f"   Experiments Run: {results['autonomous_pipeline_stats']['experiments_run']}")

        except Exception as e:
            print(f"[ERROR] Execution failed: {e}")

    # Run the example
    print("\n" + "="*80)
    print("AUTONOMOUS TIMING DATA SELECTION AGENT - MINIMAL VERSION")
    print("="*80)
    asyncio.run(main())